### ISSUE TITLE
Link giving 404 

### ISSUE THREAD

**Issue by satyaakam** [dabeaz-course/practical-python#1]
on this page  https://github.com/dabeaz-course/practical-python/blob/master/Notes/01_Introduction/00_Overview.md

the first link https://github.com/dabeaz-course/practical-python/blob/master/Notes/01_Introduction/01_Python is giving 404

**Comment by satyaakam** [comment]
checked all the link on that page they are giving 404

**Comment by satyaakam** [comment]
ah may be i spoke too soon  ;-) are you linking TOC etc

**Comment by dabeaz** [comment]
Are you viewing this on GitHub pages?   https://dabeaz-course.github.io/practical-python

**Comment by dabeaz** [comment]
General note:  I didn't see any obvious way to have the link work simultaneously on Github pages and just in the raw source of the Github repo.   But, if someone knows how to do that, I'll make a change.

**Comment by satyaakam** [comment]
manually maintaining the links is one way , but https://readthedocs.org/ can be used also , but it may be overkill , don't know what was your initial idea how you wanted to maintain it

**Comment by dabeaz** [comment]
Specifying links in the same manner as the PR did not seem to work for me when I tried it (much earlier).  Maybe there is a configuration issue with GitHub pages that I'm missing?

**Comment by dabeaz** [comment]
Got it.  I'm not why this didn't work earlier.  Maybe not enough coffee ;-).  In any event, merged the PR.  It seems to be better now. Many thanks!
