### ISSUE TITLE
Need help trying to execute .py files on git bash

### ISSUE THREAD

**Issue by wils205401** [dabeaz-course/practical-python#109]
Hi, so I am trying to follow this course. I have anaconda 3 installed (using python 3.8.3) and git bash. 

So to start the python interpreter on git bash, I typed: winpty python  which worked fine.

When I tried to execute a file, hello.py file for example, I would type: python hello.py
 it only works if the file is located C:\Users\username 

I am now working on 1.2 A First Program. In the exercise for the bouncing ball, the file required is stored here:
C:\Users\username\GitHub Projects\practical-python\Work    #bounce.py 

But because the file #bounce.py is located in a subfolder, I can't execute the script by typing: python bounce.py

I am rather new to working in a terminal and unclear about environment variables and paths, what should I do in this situation?
I want to be able to get the same output in git bash as shown on the course page.

**Comment by atsaloli** [comment]
You should be able to run the file by providing the full path to it, e.g.:

```
python "GitHub Projects\practical-python\Work\bounce.py"
```

**Comment by jingzuwu** [comment]
苹果手机输入法input输入：ryl
ryl表示：任意两renyiliang汉语拼音首字母
display显示：
a=int(input('input：任意两个数相加\n第一个数:'));b = int(input('input第二个数：'));print('两个数加法：' + str(a + b))
![1612201F-38B3-41A7-BC41-36EFD4C6700C](https://user-images.githubusercontent.com/32052848/121615697-10289e00-ca94-11eb-854b-c6956023f098.png)

**Comment by jingzuwu** [comment]
input输入：j
j表示：加jia汉语拼音首字母
display显示：
print('''《利用1+1的数学方法，进行苹果手机上如何进行编程的应用程序研究》\n吴敬祖\n云南农业大学人文学院''')
a=1;b=1;print('a=1,b=1\na+b=',a+b)
![Uploading 43F96BFB-0ED2-40D3-A1AA-665EC3F78EF3.png…]()
