### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by cenybar** [dabeaz-course/practical-python#111]
On page: https://dabeaz-course.github.io/practical-python/Notes/06_Generators/03_Producers_consumers.html

Under 'Producer-Consumer Problems' it reads:

Consumer
for line in follow(f):    # Consumes **vale** from `yield` above

Should say value instead?

Thanks for this wonderful course btw

**Comment by crowellcindy** [comment]
#- ![image](https://user-images.githubusercontent.com/38626974/99907415-493d2480-2ca2-11eb-8c6e-285251068585.jpeg)![image](https://[]()user-images.githubusercontent.com/38626974/99907430-59ed9a80-2ca2-11eb-80b3-496fc6cae4fc.jpeg)_[![image](https://user-images.githubusercontent.com/38626974/99907466-886b7580-2ca2-11eb-9929-58e3bc7423f8.jpeg)]()_D![image](https://user-images.githubusercontent.com/38626974/99907490-a33dea00-2ca2-11eb-90d5-c40a5629024d.png)

**Comment by dabeaz** [comment]
Fixed. Thanks!
