### ISSUE TITLE
Set or list in the example?

### ISSUE THREAD

**Issue by danrlu** [dabeaz-course/practical-python#113]
In this section:
https://dabeaz-course.github.io/practical-python/Notes/02_Working_with_data/02_Containers.html
![image](https://user-images.githubusercontent.com/20667188/101999050-9b200b80-3c9e-11eb-9e29-43101fe82018.png)

`names` was just mentioned in the previous code block to be a `list`, so for the `set` operation, probably the intention is `unique.add()` and `unique.remove()`? (since `tech_stocks` doesn't have "YHOO" to remove)

I'm loving this course. Had to flash refresh my memory of Python for a coding interview in 2 days and this is perfect. Thank you!!

Dan

**Comment by dabeaz** [comment]
The assignment of `names` in the example immediately above this includes `YHOO`.
