### ISSUE TITLE
Mortgage -- start and end months

### ISSUE THREAD

**Issue by atsaloli** [dabeaz-course/practical-python#115]
Hi.

I saw https://github.com/dabeaz-course/practical-python/issues/95  I have another question about the mortgage.py assignment, please.

The problem statement is:

> How much will Dave pay if he pays an extra $1000/month for 4 years starting in year 5 of the mortgage?  

a) The start month is set to 61 -- isn't that the first month of 6th year?  5 years at 12 months per year is 60 months, so 61 belongs to the sixth year, doesn't it?  Or am I counting wrong?
b) The end month is set to 108 -- why isn't it 109 (61 + 48) ?

**Comment by dabeaz** [comment]
You know, I think you might be right!   Maybe there's been too much 0-based indexing going on ;-).

**Comment by atsaloli** [comment]
Okay!  :)  

And, hey, thank you so much for open sourcing this content!!  I took your intro course at a USENIX conf years ago, just for the exposure, and now I need to use Python for my new job, and having this stuff (plus a responsive author/instructor) is a real boon.  Thank you!!  :) :)
