### ISSUE TITLE
06_List_comprehension: ]

### ISSUE THREAD

**Issue by xinhuiqin** [dabeaz-course/practical-python#118]
On page: https://dabeaz-course.github.io/practical-python/Notes/02_Working_with_data/06_List_comprehension.html
```python
>>> names = { s['name'] for s in portfolio }
>>> names
{ 'AA', 'GE', 'IBM', 'MSFT', 'CAT'] }
>>>
```
There is a square bracket ](after 'CAT') that is needless. The names value should be:
```python
>>> names = { s['name'] for s in portfolio }
>>> names
{ 'AA', 'GE', 'IBM', 'MSFT', 'CAT'}
>>>
```

**Comment by dabeaz** [comment]
Fixed.  Thanks!
