### ISSUE TITLE
Lines not counted correctly in exercises 3.9 onwards

### ISSUE THREAD

**Issue by shindere** [dabeaz-course/practical-python#121]
The header line is not taken into account for counting rows while
parsing CSV files, so that the displayed messages have a -1 shift, e.g.
Row 4 instead of Row 5, etc. This affects both the code and the content
of the text, for instance in the example output shown for exercise 3.9.

**Comment by dabeaz** [comment]
Maybe it's a bit ambiguous as to whether the line number includes the header or not.   Going leave "as is" for now.
