### ISSUE TITLE
Exercise 2.18: Tabulating with Counters

### ISSUE THREAD

**Issue by whately** [dabeaz-course/practical-python#127]
>>> portfolio = read_portfolio('Data/portfolio.csv')
>>> from collections import Counter
>>> holdings = Counter()
>>> for s in portfolio:
        holdings[s['name']] += s['shares']

The last line seems to be incorrect. It should be:
holdings[s['name']] += float(s['shares'])

**Comment by dabeaz** [comment]
The portfolio returned by `read_portfolio()` should already have shares converted to an integer.
