### ISSUE TITLE
Chapter 1 Section 7 - Missing split delimiter, code in 'Catching and Handling Exceptions'

### ISSUE THREAD

**Issue by jpiedra** [dabeaz-course/practical-python#139]
[Direct link to relevant section](https://dabeaz-course.github.io/practical-python/Notes/01_Introduction/07_Functions.html)

Apologies if there was already an issue opened for this one...
I think the example in this section, the one that illustrates the use of try/catch, is intended to read like so:
```
for line in f:
    fields = line.split(',') # the comma is currently missing
    try:
        shares = int(fields[1])
    except ValueError:
        print("Couldn't parse", line)
    ...
```

**Comment by dabeaz** [comment]
Fixed.
