### ISSUE TITLE
Minor issue with final example in exercise 3.7

### ISSUE THREAD

**Issue by jonas-bird** [dabeaz-course/practical-python#141]
I noticed that the final example in Chapter 3.2 More on Functions, at the end of exercise 3.7 shows `portfolio = parse_csv('Data/portfolio.dat', types=[str, int, float], delimiter=' ')` as at this point parse_csv() includes the has_headers argument this would return a list of tuples rather than a list of dictionaries as shown. 

Thank you for putting this course up - I have worked through several online tutorials, a couple of books, and even taken a course, but until Practical Python Programming I was never comfortable working with Python

**Comment by dabeaz** [comment]
The `has_headers` argument is set to `True` by default so this operation should return a list dictionaries.
