### ISSUE TITLE
Suggestion for exercise 2.5

### ISSUE THREAD

**Issue by Nick-Z0** [dabeaz-course/practical-python#148]
Hi Dave,

The instructions to arrive at the solution of exercise 2.5 are not very clear. What I mean is that until this point all exercises were doable without researching external content; all info needed was provided in the lessons beforehand.
Specifically, the zip function as in shown in the proposed solution file of 2.16 is not taught in the lesson above:
```
for row in rows:
            record = dict(zip(headers, row))
            stock = {
                 'name'   : record['name'],
                 'shares' : int(record['shares']),
                 'price'   : float(record['price'])
            }
            portfolio.append(stock)
```

I suggest to either add some hint as with previous exercises or encourage the student to research external sources if he is stuck.

P.S.: Thanks for this great course, I am enjoying it very much!

**Comment by dabeaz** [comment]
I don't follow.  The above code isn't related to Exercise 2.5.   The example of producing a dictionary using zip() is shown in the section prior to exercise 2.16.
