### ISSUE TITLE
Broken links in section 3.2 More on Functions

### ISSUE THREAD

**Issue by TheOutlawstar** [dabeaz-course/practical-python#153]
There are three links in the 3.2 More on Functions page, which when clicked go to 404 not found. I have not checked any other pages (yet...).

Argument Passing
When you call a function, the argument variables are names that refer to the passed values. These values are NOT copies (see [section 2.7](https://github.com/dabeaz-course/practical-python/blob/master/Notes/02_Working_with_data/07_Objects)).

An example of a column selector was given in [Exercise 2.23](https://github.com/dabeaz-course/practical-python/blob/master/Notes/02_Working_with_data/06_List_comprehension). However, here’s one way to do it:

You already explored this in [Exercise 2.24](https://github.com/dabeaz-course/practical-python/blob/master/Notes/02_Working_with_data/07_Objects). You'll need to insert the following fragment of code into your solution:

**Comment by dabeaz** [comment]
These links for for me on https://dabeaz-course.github.io/practical-python/Notes/03_Program_organization/02_More_functions.html

Are you viewing the course somewhere else?

**Comment by TheOutlawstar** [comment]
I'm viewing the course at this URL: https://github.com/dabeaz-course/practical-python/blob/master/Notes/03_Program_organization/02_More_functions.md

**Comment by dabeaz** [comment]
Fixed.
