### ISSUE TITLE
Section 3.4 exercise numbering discrepancy

### ISSUE THREAD

**Issue by TheOutlawstar** [dabeaz-course/practical-python#155]
In section/chapter 3.4, the two exercises at the bottom of the page are 3.12 and 3.14. There is no exercise 3.13, not sure if that is intentional.

https://github.com/dabeaz-course/practical-python/blob/master/Notes/03_Program_organization/04_Modules.md

![image](https://user-images.githubusercontent.com/12189717/204072538-22a1b99a-54f6-409d-8a0a-14f7b46bf8df.png)

**Comment by dabeaz** [comment]
There is no exercise 3.13.   I'll make an edit to note that.
