### ISSUE TITLE
Typo in section 5.2

### ISSUE THREAD

**Issue by TheOutlawstar** [dabeaz-course/practical-python#156]
The Managed Attributes portion of 5.2 has a typo in the code sample which I found slightly confusing as a novice programmer. I thought it might be needed as its referencing a setter, but then I realized its just a typo :)

class Stock:
    def __init__(self, name, shares, price):
        self.name = name
	    **self.set_shares(shares)
	    self.price = price**

https://github.com/dabeaz-course/practical-python/blob/master/Notes/05_Object_model/02_Classes_encapsulation.md#managed-attributes

**Comment by dabeaz** [comment]
Fixed (the indentation issue).  Thanks!
