### ISSUE TITLE
CTA 22 Bus Hours

### ISSUE THREAD

**Issue by PeterWAWood** [dabeaz-course/practical-python#19]
It seems that route 22 does not have.24 hours service. If you try the Exercise 1.4  when the service is not in operation nothing gets printed:
```Python
>>> u = urllib.request.urlopen('http://ctabustracker.com/bustime/map/getStopPredictions.jsp?stop=14791&route=22')
>>> doc = parse(u)
>>> for pt in doc.findall('.//pt'):
...     print(pt.text)                                                          ... 
>>> 
```

This might be worrying for someone who is new to Python. After viewing the xml via a browser, I was able to work out why there was no output.
```Python
>>> for pt in doc.findall('.//noPredictionMessage'):                            ...     print(pt.text)
... 
No arrival times
```

I did manage to get an arrival time using route 5 & stop 12023 but that seems to be a night only service. (I have never visited Chicago).
```Python
>>> u = urllib.request.urlopen('http://ctabustracker.com/bustime/map/getStopPredictions.jsp?stop=12023&route=5')
>>> doc = parse(u)
>>> for pt in doc.findall('.//pt'):                                             ...     print(pt.text)                                                          ... 
APPROACHING
24 MIN
```

Perhaps a word of warning could be given along the lines of 

"If you try this in the middle of the night or live overseas, there may be no buses running on route 22. If you don't see a list of pending arrivals, try to check for bus route 5 at stop 12023."

**Comment by dabeaz** [comment]
Good idea.   Added a short note about the tracker not showing any results beyond 30 minutes.

**Comment by Jock2018** [comment]
Thanks. It's useful!
