### ISSUE TITLE
Typo in chapter 5

### ISSUE THREAD

**Issue by xtrntr** [dabeaz-course/practical-python#20]
https://github.com/dabeaz-course/practical-python/blob/master/Notes/05_Object_model/01_Dicts_revisited.md#method-resolution-order-or-mro

> ... called the Method Resolutin Order. The find an attribute, Python walks the MRO in order...

**Comment by xtrntr** [comment]
https://github.com/dabeaz-course/practical-python/blob/master/Notes/05_Object_model/01_Dicts_revisited.md#mro-in-multiple-inheritance

> What happens when you access at attribute?

**Comment by dabeaz** [comment]
Fixed!
