### ISSUE TITLE
"You may never use _ in a program."

### ISSUE THREAD

**Issue by dTanMan** [dabeaz-course/practical-python#23]
Hi! This line from [Section 1.2, Hello World](https://github.com/dabeaz-course/practical-python/blob/master/Notes/01_Introduction/02_Hello_world.md) about underscores bothered me a bit:

> This is only true in the interactive mode. **You never use _ in a program.**

Is the latter part safe to say? Since the _ character can be used as a throwaway, right? Like if I want a list to contain 5 boolean values, I can do:

```
tracker = [True for _ in range(5)]
```

Maybe it can be worded as, "the underscore has a different purpose in non-interactive mode." Apologies if this is amended later on and I just haven't gotten to that part.

That aside, congratulations on this book. Loving it so far! Apologies too if I'm using GitHub incorrectly -- I'm kinda new to this.

**Comment by dabeaz** [comment]
Someone learning Python for the first time, having seen `_` in the REPL might immediately wonder if that's a general feature of the language.  It is not.  They are not wondering about throwaway variables or other uses of `_`.     The course is not meant to be a Python reference manual so there are a LOT of omissions like this in the interest of having a coherent narrative without getting sidetracked into unrelated topics.  Sometimes further details get filled in later.  Sometimes not.
