### ISSUE TITLE
Typo section 2.1 'ommitted'

### ISSUE THREAD

**Issue by bobhilt** [dabeaz-course/practical-python#30]
"Sometimes the () are ommitted in the syntax."
https://dabeaz-course.github.io/practical-python/Notes/02_Working_with_data/01_Datatypes.html

**Comment by dabeaz** [comment]
Fixed!

**Comment by Peppeli** [comment]
Still didn't work, I have to field in a default value.. Still searching up
how to do that

**Comment by dabeaz** [comment]
What didn't work?   Example?
