### ISSUE TITLE
Minor suggestion: mention bytes strings in exercise 1.28?

### ISSUE THREAD

**Issue by meitros** [dabeaz-course/practical-python#37]
In exercise 1.28 you're looking at a gzipped file of the same portfolio data file from the previous exercises. One can't just substitute in the gzip `with` command, though, since now you'll get byte strings back. I think it's worth adding a sentence clarifying this: IMO it's a bit unexpected for the reader since the compressed content is still a text file (and more reinforcement of the fact that byte strings and regular strings are different can only be a good thing.)

**Comment by dabeaz** [comment]
Fixed.
