### ISSUE TITLE
`\Notes\02_Working_with_data\02_Containers.md`  Error after code runs:

### ISSUE THREAD

**Issue by liujuanjuan1984** [dabeaz-course/practical-python#40]
`\Notes\02_Working_with_data\02_Containers.md`

Error after code runs:

```python
records = []  # Initial empty list

with open('Data/portfolio.csv', 'rt') as f:
    for line in f:
        row = line.split(',')
        records.append((row[0], int(row[1])), float(row[2]))
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-fd7df5280ae9> in <module>
      2 
      3 with open('Work/Data/portfolio.csv', 'rt') as f:
----> 4     for line in f[1:]:
      5         row = line.split(',')
      6         records.append((row[0], int(row[1])), float(row[2]))

TypeError: '_io.TextIOWrapper' object is not subscriptable

**Comment by dabeaz** [comment]
Files can't be indexed or sliced.
