### ISSUE TITLE
if anyone  needs markdown file trans to Jupyte Notebook files?

### ISSUE THREAD

**Issue by liujuanjuan1984** [dabeaz-course/practical-python#41]
Hi, @dabeaz  or anyone there:

As a beginner of Python,  I used Jupyter Notebook a lot and so LOVE it.

It's my pleasure to trans all markdown file of this repo to Jupyter Notebook file `.ipynb`.

but I am not sure:

> Is it usefull for anyone else?
> Will @dabeaz need it if i pull a `Pull Request`?

![image](https://user-images.githubusercontent.com/31027645/83883021-89046400-a775-11ea-8800-4f1f8aa4a65d.png)

**Comment by dabeaz** [comment]
The course notes about setup are explicit about not using Jupyter notebooks.   This is not meant as a negative comment about notebooks, but later portions of the course (starting in section 3) start to do a lot with files, module imports, and other concepts related to code organization.  I have never seen this work well in notebooks in all of my years of teaching the material. 

Also, I think people will get more out of the course by being forced to type in the examples by hand, slowly, and thinking about what they're doing as opposed to hitting "enter" in a notebook cell.    

So, a notebook version of the course is not something that I would pull into the main repo.  Of course, as all of this material is Creative Commons, I'm more than happy to add a link to a notebook version someone has created elsewhere.

**Comment by Babu-SKK** [comment]
@liujuanjuan1984  I am very much interested in Jupyter notebooks. Can you give me access?
