### ISSUE TITLE
Couple of typos in page 5.1 Dictionaries Revisited

### ISSUE THREAD

**Issue by billtubbs** [dabeaz-course/practical-python#42]
Just some minor typos I found:

1. Replace "a collection of names values" with "a collection of named values"
2. Replace "A attribute search process" with "An attribute search process"
3. In the code snippet 'Dicts and Objects', replace `{'name' : 'GOOG','shares' : 100, 'price': 490.1 }` with `{'name' : 'GOOG', 'shares' : 100, 'price': 490.1 }` (additional space).

Thanks, great work!

**Comment by dabeaz** [comment]
Fixed!  Thanks.
