### ISSUE TITLE
Chapter 1.6 File Management missing foo.txt might be confusing for new python users

### ISSUE THREAD

**Issue by dev-mbusch** [dabeaz-course/practical-python#51]
Hi Dave,

just working through the Practical Python course in preparation for the Advanced Python Course in July.

In the chapter 1.6 right at the start you are showing an example of how to read a file:

`f = open('foo.txt', 'rt')     # Open for reading (text)`

The file doesn't exist in the Work folder so an exception occurs that might be confusing for people. 

I think there should be a example file. Or even better reverse the order of reading and writing to a file and let the people first write some text to a file "foo.txt" and let them read it in again afterwards.

**Comment by dabeaz** [comment]
The notes portion of this section is fairly short before it jumps to exercises.   Going to leave it "as is" for now.
