### ISSUE TITLE
Section 1.2: sampled code for Looping and Indentation not consistent

### ISSUE THREAD

**Issue by arvinquilao** [dabeaz-course/practical-python#57]
In section 1.2 the following example is used for Looping and Indentation:

    while num_bills * bill_thickness < sears_height:
        print(day, num_bills, num_bills * bill_thickness)
        day = day + 1
        num_bills = num_bills * 2

    print('Number of days', days)

If the intention is to sample a portion of the previously shown solution, then the last line should say ` print('Number of days', day)` to make it consistent.

**Comment by dabeaz** [comment]
I don't see an indentation issue here, but did fix the "days" -> "day" typo.
