### ISSUE TITLE
"Home" link on Contents.md page gives 404 error

### ISSUE THREAD

**Issue by celtic-coder** [dabeaz-course/practical-python#66]
## Anchor on GitHub.com page

The home page for the course, on GitHub.com, has the anchor [Take me to the Course Already!](https://github.com/dabeaz-course/practical-python#take-me-to-the-course-already) and the following text:

> Ok, ok. Point your browser HERE!

Where [HERE](https://github.com/dabeaz-course/practical-python/blob/main/Notes/Contents.md) links to the **Contents.md** page (part of the "blob" directory tree).

However, the [Home](https://github.com/dabeaz-course/practical-python/blob/main) link at the bottom of that page is generating a 404 Page Not Found error as it is not returning to the correct point in the "blob" directory tree.

The Markdown code for the link is:

````
[Home](..)
````

Perhaps it should be the following?

````
[Home](..\..)
````

## Link to https://dabeaz-course.github.io/

I found the link to this GitHub repo on [Hacker News](https://news.ycombinator.com/item?id=23549273). However, it was only in looking at Issue #1 that I realized that the repo is mirrored at https://dabeaz-course.github.io/practical-python/.

There is a link from the GitHub.io page to the GitHub.com repo, but there is no link, that I can see, from the GitHub repo going in the opposite direction. Did I miss something, perhaps?

The [Contents](https://dabeaz-course.github.io/practical-python/Notes/Contents.html) page on GitHub.io has the correct **Home** link. I do not know how the repo and the GitHub.io pages are related, so I'm not sure if the issue mentioned above can be corrected without causing some negative impact.

**Comment by dabeaz** [comment]
Fixed.
