### ISSUE TITLE
Section 1.1: false statement about the REPL

### ISSUE THREAD

**Issue by yujiri8** [dabeaz-course/practical-python#67]
`Warning: It is never possible to paste more than one Python command (statements that appear after >>>) to the basic Python shell at a time. You have to paste each command one at a time.`

This is false, at least on FreeBSD with xfce4-terminal. I've been using Python for 6 years and can't remember this ever being true.

**Comment by dabeaz** [comment]
The `>>>` prompt is not valid Python.  You can't just take the output of an interactive session as shown and paste it at the prompt.  Sorry.

```
>>> import urllib.request
>>> >>> u = urllib.request.urlopen('http://ctabustracker.com/bustime/map/getStopPredictions.jsp?stop=14791&route=22')
  File "<stdin>", line 1
    >>> u = urllib.request.urlopen('http://ctabustracker.com/bustime/map/getStopPredictions.jsp?stop=14791&route=22')
     ^
SyntaxError: invalid syntax
>>> >>> from xml.etree.ElementTree import parse
  File "<stdin>", line 1
    >>> from xml.etree.ElementTree import parse
     ^
SyntaxError: invalid syntax
>>> >>> doc = parse(u)
  File "<stdin>", line 1
    >>> doc = parse(u)
     ^
SyntaxError: invalid syntax
>>> >>> for pt in doc.findall('.//pt'):
  File "<stdin>", line 1
    >>> for pt in doc.findall('.//pt'):
     ^
SyntaxError: invalid syntax
>>>         print(pt.text)
  File "<stdin>", line 1
    print(pt.text)
    ^
IndentationError: unexpected indent
>>> 
```

**Comment by yujiri8** [comment]
Sorry, I guess I misunderstood the statement. I interpreted it as meaning you couldn't paste multiple commands into the prompt at once, rather than that you couldn't paste them including the `>>>`. I would recommend clarifying the wording (it's not the pasting of the multiple commands at once that's invalid, but the inclusion of the `>>>`, regardless of how many lines you include).

**Comment by dabeaz** [comment]
Pasting multiple commands (even without the >>>) also fails in environments such as IDLE.

**Comment by dabeaz** [comment]
Example (from IDLE), pasting two print statements on separate lines.   

```
Python 3.8.1 (default, Jan  8 2020, 16:15:59) 
[Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> print("hello")
print("world")
SyntaxError: multiple statements found while compiling a single statement
>>> ```
