### ISSUE TITLE
section 7.2: "Using Lambda" incorrectly states that "if/else" are not allowed in lambda expressions

### ISSUE THREAD

**Issue by norweeg** [dabeaz-course/practical-python#73]
The third bullet point of [this section](https://github.com/dabeaz-course/practical-python/blob/master/Notes/07_Advanced_Topics/02_Anonymous_function.md#using-lambda) is incorrect.  Lambdas may contain if/else. 

For example:

```
In [1]: f=lambda x: "Negative" if x<0 else "Positive"

In [2]: f(1)
Out[2]: 'Positive'

In [3]: f(-11)
Out[3]: 'Negative'
```

**Comment by dabeaz** [comment]
The bullet point clearly says "statements" of which "if" is an example.

```
if expr:
    ...
else:
    ...
```

The example you show is a conditional expression, which aside from using the "if" keyword, is not the same thing as an if-statement.    This feature of Python does not appear anywhere else in the course.  So, it would be confusing to suddenly show an example of it here.
