### ISSUE TITLE
Script improvement in Chapter 3.1

### ISSUE THREAD

**Issue by vraez** [dabeaz-course/practical-python#75]
Hello dabeaz,

when I took the course I had to modify the marked a part of the script to make it work (Chapter 3.1, last script at the bottom):

'prices.csv' --> 'Data/prices.csv'

![image](https://user-images.githubusercontent.com/62477534/86122917-e079c380-bad8-11ea-849f-25a90c9db9bf.png)

Just a minor improvement to your awesome course.

Cheers,
vraez

**Comment by dabeaz** [comment]
Fixed!  Good catch.
