### ISSUE TITLE
Typo in Datatypes markdown

### ISSUE THREAD

**Issue by lonebrave** [dabeaz-course/practical-python#76]
Notes/02_Working_with_data/01_Datatypes.md has a typo for the price value in the third code block of Exercise 2.2. It says the price is 75 when it should be 32.2, as the shares value was updated to 75, not the price value.

Diff:
@@ -338,7 +338,7 @@ above. Change the number of shares to 75.
 ```python
 >>> d['shares'] = 75
 >>> d
-{'name': 'AA', 'shares': 75, 'price': 75}
+{'name': 'AA', 'shares': 75, 'price': 32.2}
 >>>
 ```

**Comment by dabeaz** [comment]
Fixed!
