### ISSUE TITLE
Add percentage format in 2.3 Formatting

### ISSUE THREAD

**Issue by tweakimp** [dabeaz-course/practical-python#9]
Not be confused with the C-style formatting.

I think it would be helpful to let the reader know that you can do this:

```python
>>> a_third = 1/3
>>> f'{a_third:.2%}' 
'33.33%'
```

**Comment by dabeaz** [comment]
There are many omissions in formatting because certain features are never used in the course.   There are links to documentation that describe the formatting in more details.
