### ISSUE TITLE
Exercise2.15

### ISSUE THREAD

**Issue by Realiamanatom** [dabeaz-course/practical-python#93]
How can I cope with the Exercise2.15? Could you please give me an answer?

**Comment by dabeaz** [comment]
What is the issue with Exercise 2.15?

**Comment by Realiamanatom** [comment]
> What is the issue with Exercise 2.15?

I don't know how to write the code in the "try" part.

**Comment by Realiamanatom** [comment]
I don’t know how to write the code in the “try” part. So I cannot get the right display as above.[cid:image005.png@01D65ECA.385EF400][cid:image006.png@01D65ECA.385EF400]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dabeaz** [comment]
There is a `Solutions` directory that has worked out code in it.   Exercises build upon each other so you'll find code in the solution for later exercises (for example, in `Solutions/2_16`).

**Comment by Realiamanatom** [comment]
Ok, I will check it later. Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
