### ISSUE TITLE
exercise1_10

### ISSUE THREAD

**Issue by josimp** [dabeaz-course/practical-python#94]
Why can't I get my loop to run like the example? I have been messing with it for a while.  I have the right answer but mine looks different lol.  Specifically my extra_payment_start_month is set to 60.
`
# mortgage.py
#
# Exercise 1.7
m = 500000.00
i = 0.05
p = 2684.11
t = 0.00
month = 0

extra_payment_start_month = 60
extra_payment_end_month = 108
extra_payment = 1000

while m > 0:
	if (month >= extra_payment_start_month) and (month < extra_payment_end_month):
		m = m * (1+i/12) - p - extra_payment
		t = t + p + extra_payment
		month += 1
		print('BONUS','month:', month, 'paid:', round(t,2), "Remaining principle:", round(m,2))
		continue
	if m <= p:
		t += m
		m = 0
		month += 1
		print("LAST", 'month:', month, 'paid:', round(t,2), "Remaining principle:", round(m,2))
		break
	m = m * (1+i/12) - p
	t = t + p
	month += 1

	print("OUTER", 'month:', month, 'paid:', round(t,2), "Remaining principle:", round(m,2))
`

**Comment by josimp** [comment]
Sorry I'm a noob and I'm not sure how to format that better.

**Comment by josimp** [comment]
[1-10.txt](https://github.com/dabeaz-course/practical-python/files/4951456/1-10.txt)

**Comment by josimp** [comment]
`# mortgage.py
#
# Exercise 1.7
m = 500000.00
i = 0.05
p = 2684.11
t = 0.00
month = 0

extra_payment_start_month = 60
extra_payment_end_month = 108
extra_payment = 1000

while m > 0:
`	if (month >= extra_payment_start_month) and (month < extra_payment_end_month):`
`		m = m * (1+i/12) - p - extra_payment`
		t = t + p + extra_payment
		month += 1
		print('BONUS','month:', month, 'paid:', round(t,2), "Remaining principle:", round(m,2))
		continue
	if m <= p:
		t += m
		m = 0
		month += 1
		print("LAST", 'month:', month, 'paid:', round(t,2), "Remaining principle:", round(m,2))
		break
	m = m * (1+i/12) - p
	t = t + p
	month += 1

	print("OUTER", 'month:', month, 'paid:', round(t,2), "Remaining principle:", round(m,2))`

**Comment by kintumiku** [comment]
You need to save file as .py and check line 23.
