### ISSUE TITLE
Mortgage

### ISSUE THREAD

**Issue by mar-due** [dabeaz-course/practical-python#95]
I tried to solve the Mortgage Exercise.

```
principal = 500000.0
rate = 0.05
payment = 2684.11
total_paid = 0.0
extra_payment_start_month = 61
extra_payment_end_month = 108
extra_payment = 1000
month = 0

while principal > 0:
    month = month + 1
    if month >= extra_payment_start_month and month <= extra_payment_end_month:
        principal = principal * (1 + rate / 12) - payment - extra_payment
        total_paid = total_paid + payment + extra_payment
    else:
        principal = principal * (1 + rate / 12) - payment
        total_paid = total_paid + payment
    if principal < 0:
        total_paid = total_paid+principal
        principal = 0
    print(month,total_paid,principal)

print('Total paid',total_paid)
print('Month', month)
```

However. I get different numbers. Not only for the corrected payment and principal at the end....even before.

I honestly cannot find an error in my code?! Any advise or hint?

**Comment by dabeaz** [comment]
It's very difficult to offer much assistance without also seeing the numbers in question.  There have been many minor edits/pull requests/bugs on the mortgage problem.   So, what are you expecting to see versus what are you actually getting?  Do the numbers match the current problem description in the main repo branch?   Have you looked at code in the Solutions directory?

**Comment by mar-due** [comment]
i am getting this:

```
306 869337.6599999964 8784.87133271253
307 872021.7699999964 6137.364963265498
308 874705.8799999964 3478.8273172791037
309 877389.9899999964 809.2124311010998
310 878202.5741495604 0
Total paid 878202.5741495604
Month 310
```
and expecting this according to your exercise description:

```
308 874705.88 2971.43
309 877389.99 299.7
310 880074.1 -2383.16
Total paid 880074.1
Months 310
```

Your solution calculates the following:
```
308 874705.88 3478.83
309 877389.99 809.21
310 880074.1 -1871.53
Total paid 880074.1
Months 310
```
So my solution seems to be correct because the given solution does not correct the sub-zero issue.

Sorry, next time i check your solutions first! ;)

Maybe you could update the exercise-description so that others do not get confused.

Thanks for your answer.

**Comment by dabeaz** [comment]
I would double-check the edge conditions of the starting and ending months.   The problem says "starting in year 5" which, depending on how you are counting, might start in month 61.      There has been some prior discussion of this and a few minor corrections.   I'm pretty sure the current revision is correct, but will double check again.

**Comment by mar-due** [comment]
We actually have the same numbers (if i remove the zero correction). So i am fine with my solution. I just wanted to mention that your exercise description might be outdated (the given numbers) because it differs to your numbers in your solution-directory. 

Your exercise description
```
308 874705.88 2971.43
309 877389.99 299.7  
310 880074.1 -2383.16
Total paid 880074.1
Months 310
```
Your Solution
```
308 874705.88 3478.83
309 877389.99 809.21
310 880074.1 -1871.53
Total paid 880074.1
Months 310
```
the "principal" after "total_paid" is different.
